# Generated by Django 4.0.4 on 2022-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentText', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeveloperName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocalizationName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublisherName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgeRestriction', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('CategoryId', models.ManyToManyField(default=None, related_name='Category', to='Games.category')),
                ('CommentId', models.ManyToManyField(default=None, related_name='Comment', to='Games.comment')),
                ('CountryId', models.ManyToManyField(default=None, related_name='Country', to='Games.country')),
                ('CurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Currency', to='Games.currency')),
                ('DeveloperId', models.ManyToManyField(default=None, related_name='Developer', to='Games.developer')),
                ('LocalizationId', models.ManyToManyField(default=None, related_name='Localization', to='Games.localization')),
                ('PublisherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publisher', to='Games.publisher')),
                ('StatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status', to='Games.status')),
            ],
        ),
    ]
