# Generated by Django 4.0.4 on 2022-06-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='GameName',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
