# Generated by Django 4.0.4 on 2022-06-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_role_siteuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='User',
            new_name='user',
        ),
    ]
